trigger:
- main

pool:
  name: 'Default'

variables:
  businessCentralUrl: 'http://40.112.52.80:8080/business-central/rest'
  kieServerUrl: 'http://40.112.52.80:8180/kie-server/services/rest/server'
  containerId: 'BPM-Process'  # Adjust this as necessary
  spaceName: 'MySpace'
  projectName: 'BPM-Process'
  githubRepoUrl: 'https://github.com/abubakar1o/integration-tests-jbpm.git'
  kieUsername: admin
  kiePassword: admin

stages:
- stage: SetupAndDeploy
  displayName: Setup and Deploy in Business-Central
  jobs:
  - job: SetupProject
    displayName: 'Setup and Import Project'
    steps:
    - bash: |
        echo "Cloning project from GitHub..."
        cloneResponse=$(curl -s -X POST -u "$kieUsername:$kiePassword" \
          "$businessCentralUrl/spaces/$spaceName/git/clone" -H "content-type: application/json" \
          -d "{\"gitURL\": \"$githubRepoUrl\"}")
        echo $cloneResponse
      displayName: 'Clone GitHub Project'

    - bash: |
        echo "Installing and deploying project via Maven..."
        compileResponse=$(curl -v -X POST -u "$kieUsername:$kiePassword" \
          "$businessCentralUrl/spaces/$spaceName/projects/$projectName/maven/compile")
        echo "Compile Response: $compileResponse"
        installResponse=$(curl -v -X POST -u "$kieUsername:$kiePassword" \
          "$businessCentralUrl/spaces/$spaceName/projects/$projectName/maven/install")
        echo "Install Response: $installResponse"
        deployResponse=$(curl -v -X POST -u "$kieUsername:$kiePassword" \
          "$businessCentralUrl/spaces/$spaceName/projects/$projectName/maven/deploy")
        echo "Deploy Response: $deployResponse"
      displayName: 'Build and Deploy Project'

    - bash: |
        echo "Deploying project to KIE Server..."
        echo "URL being used: $fullUrl"  # This will help you verify that the URL is correct.
        kieDeployResponse=$(curl -X PUT -u "admin:admin" \
          "http://40.112.52.80:8180/kie-server/services/rest/server/containers/BPM-Process" -H 'Content-Type: application/json' \
          -d '{
            "container-id": "BPM-Process",
            "release-id": {
              "group-id": "org.example",
              "artifact-id": "BPM-Process",
              "version": "1.0"
            },
            "status": "STARTED"
          }')
        echo "KIE Server Deploy Response: $kieDeployResponse"
      displayName: 'Deploy to KIE Server'
