trigger:
- main

pool:
  name: 'Default'

variables:
  kieServerUrl: 'http://40.112.52.80:8180/kie-server/services/rest/server'
  businessCentralUrl: 'http://40.112.52.80:8080/business-central/rest'
  spaceName: 'MySpace'
  projectName: 'BPM-Process'
  githubRepoUrl: 'https://github.com/abubakar1o/integration-tests-jbpm.git'
  kieUsername: admin
  kiePassword: admin

stages:
- stage: SetupAndDeploy
  displayName: Setup and Deploy in Business-Central
  jobs:
  - job: SetupProject
    displayName: 'Setup and Import Project'
    steps:
    - bash: |
        echo "Cloning project from GitHub..."
        cloneResponse=$(curl -s -X POST -u "${{ variables.kieUsername }}:${{ variables.kiePassword }}" \
          "${{ variables.businessCentralUrl }}/spaces/${{ variables.spaceName }}/git/clone" -H "content-type: application/json" \
          -d "{\"gitURL\": \"${{ variables.githubRepoUrl }}\"}")
        echo $cloneResponse
      displayName: 'Clone GitHub Project'
    - bash: |
        echo "Installing and deploying project via Maven..."
        curl -v -X POST -u "${{ variables.kieUsername }}:${{ variables.kiePassword }}" \
          "${{ variables.businessCentralUrl }}/spaces/${{ variables.spaceName }}/projects/${{ variables.projectName }}/maven/compile"
        curl -v -X POST -u "${{ variables.kieUsername }}:${{ variables.kiePassword }}" \
          "${{ variables.businessCentralUrl }}/spaces/${{ variables.spaceName }}/projects/${{ variables.projectName }}/maven/install"
        curl -v -X POST -u "${{ variables.kieUsername }}:${{ variables.kiePassword }}" \
          "${{ variables.businessCentralUrl }}/spaces/${{ variables.spaceName }}/projects/${{ variables.projectName }}/maven/deploy"
      displayName: 'Build and Deploy Project'

    - bash: |
        echo "Deploying Container in KIE Server..."
        curl -v -X post -u "${{ variables.kieUsername }}:${{ variables.kiePassword }}" \
          "${{ variables.kieServerUrl }}/containers/${{ variables.kieContainerId }}" -H 'Content-Type: application/json' \
          -d "{
            \"container-id\": \"${{ variables.kieContainerId }}\",
            \"release-id\": {
              \"group-id\": \"${{ variables.projectName }}\",
              \"artifact-id\": \"${{ variables.projectName }}\",
              \"version\": \"1.0\"
            }
          }"
      displayName: 'Deploy Container'